### ISSUE TITLE
v0.7.15 tolerations being rendered incorrectly

### ISSUE THREAD

**Issue by d-shi** [quickwit-oss/helm-charts#132]
Setting this in the values.yaml file:

```
searcher:
  tolerations:
    - effect: NoSchedule
      key: role
      operator: Equal
      value: quickwit
```

results in a tendered template that looks like this:

```
      tolerations:
        - - effect: NoSchedule
            key: role
            operator: Equal
            value: quickwit
```

which gives this error on apply:

`* StatefulSet in version "v1" cannot be handled as a StatefulSet: json: cannot unmarshal array into Go struct field PodSpec.spec.template.spec.tolerations of type v1.Toleration`

I had to update the values.yaml config to not include the hyphen to make it work, but would not work if I needed to include multiple:

```
searcher:
  tolerations:
    effect: NoSchedule
    key: role
    operator: Equal
    value: quickwit
```
