### ISSUE TITLE
Add filebacked metastore default config in values.yaml

### ISSUE THREAD

**Issue by fmassot** [quickwit-oss/helm-charts#39]

**Comment by imotov** [comment]
I was about to open an issue for that 😄 I can take a look at this as a follow up for quickwit-oss/quickwit#3164.

**Comment by fmassot** [comment]
That would be great. The PR #43 tries to solve the issue by defining the `metastore_uri` but... adding a metastore uri is bit confusing when you define a postgres config. We probably want some validation too (#44).

This is what I have in mind:

```yaml
config:
  metastore:
    # Define the URI.
    uri: s3://bucket/indexes 
    # uri: postgres://username:password@host:port/database 
    # You  can also define a postgres metastore like this
    # postgres:
    #   host: ""
    #   port: 5432
    #   database: metastore
    #   username: quickwit
    #   password: ""
```

Honestly, I would prefer removing the `postgres`, @clemcvlcs any thoughts on this?
