### ISSUE TITLE
Autoscaling with KEDA

### ISSUE THREAD

**Issue by idrissneumann** [quickwit-oss/helm-charts#54]
Is-it possible to add a flag to enable the KEDA autoscaler for the searcher and indexer pods. Something we could enabled in the `values.yaml` like that:

```yaml
keda:
  indexer:
     enabled: true
     # metrics used for scale
  searcher:
     enabled: true
     # metrics used for scale
```
